version: "1"

services:
    mysql:
     image: mysql:5.7
     container_name: compose-mysql
     ports:
      - "3301:3306"
     volumes:
      - "/root/temp/compose-demo/conf:/etc/mysql/conf.d"
      - "/root/temp/compose-demo/logs:/logs"
      - "/root/temp/compose-demo/data:/var/lib/mysql"
     command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
     ]
     restart: always
       networks:
         extnetwork:
           ipv4_address: 172.17.0.2
     environment:
       MYSQL_ROOT_PASSWORD: "root"

    redis:
      image: redis:latest
      container_name: compose-redis
      ports:
       - "6380:6379"
      volumes:
       - "/root/temp/compose-demo/redis_data:/data"
      restart: always
        networks:
          extnetwork:
            ipv4_address: 172.17.0.3

    compose-java:
     build: ./java
     image: compose-java:v1
     container_name: compose-java
     ports:
      - "8091:8091"

networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.17.0.0/16
          gateway: 172.17.0.1